name: flutter_appauth_platform_interface
description: A common platform interface for the flutter_appauth plugin.
version: 3.0.0
homepage: https://github.com/MaikuB/flutter_appauth/tree/master/flutter_appauth_platform_interface

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: 

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 
